services:
  - type: web
    name: api-estudiantes
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false
    pythonVersion: 3.11.9
